### DISCUSSION TITLE
config/style

### DISCUSSION THREAD

**Discussion by giscus** [ATQQ/sugar-blog#202] [Announcements]
# config/style

介绍一下自定义主题的部分样式

https://theme.sugarat.top/config/style.html

**Comment by BinMist** [comment]
怎么设置不要背景图呢

**Reply by ATQQ** [reply]
background-image: none;

这样即可

**Comment by SuZhelevel6** [comment]
~~~
    interface HomeBlog {
        name?: string;
        motto?: string;
~~~
请问主页的blog中的name和motto的样式是在哪里定义的呢？我想改动他的大小和颜色。

**Reply by ATQQ** [reply]
复写CSS 样式即可
```css
.header-banner h1>span.name{
  color: red;
}

.header-banner h1>span.motto{
  color: green;
}
```

然后再 theme/index.ts 中引入 样式

<img width="564" alt="image" src="https://github.com/user-attachments/assets/3bab5639-b255-4534-a3e6-17ccd53747c1">
