### ISSUE TITLE
[idea]右侧导航栏能否实现固定,不随着文章列表的滚动而随之滚动

### ISSUE THREAD

**Issue by zxxj** [ATQQ/sugar-blog#162]
<img width="1394" alt="image" src="https://github.com/ATQQ/sugar-blog/assets/96833320/c7fc6d5e-720b-46cf-8716-346f5a7a5732">

如上图,我目前想实现右侧导航栏固定,但我调试了很久,无法成功,会影响到左侧文章列表的布局与移动端的适配,特此来请教有无好的解决方式~

**Comment by ATQQ** [comment]
了解的 应该只用调整样式就可以 我看一下

**Comment by ATQQ** [comment]
![Kapture 2024-01-03 at 21 22 03](https://github.com/ATQQ/sugar-blog/assets/42485491/d26fcb38-66f6-4033-9e37-7261ee0f3d85)


你看是这种效果吗，这回有一个问题，如果你卡片内容比较长，固定的话 下面的内容没法显示呀

**Comment by ATQQ** [comment]
PC 的固定你加下面 这段样式就可以了
```css
@media screen and (min-width: 768px){
  #VPContent div.blog-info-wrapper{
    position: relative !important;
    width: 300px;
  }

  #VPContent div.blog-info{
    position: fixed !important;
    /* top 根据自己的实际情况调整 */
    /* top: 200px; */
  }

  /* 其它的你根据实际的dom结构调整你想要的高度滚动啥的即可 */
}
```
