### ISSUE TITLE
pagefind插件，如果md中出现<script setup lang="ts">标签将无法索引

### ISSUE THREAD

**Issue by XiaofengdiZhu** [ATQQ/sugar-blog#263]
会出现`may not be a valid file, will not be indexed, please contact the author for assistance`  
去掉`lang="ts"`即可，但还是希望解决，谢谢  
如果只去掉`setup`，也不会报错~但我的vue组件就显示不出来了  

另外，对自定义vue组件的支持不太好，我这好像只能索引到vue组件里最后一个h标签及其之后的内容，没继续深入研究，而vitepress自带搜索能搜到全部内容  

最后，希望内容预览能像原版那样带css样式带图片

**Comment by ATQQ** [comment]
可以先回退的 0.4.3 版本试一试。上周上了 一个feature 可能有些影响

**Comment by ATQQ** [comment]
预览的那个能力，不一定好做，这个得研究一下 [pagefind](https://pagefind.app/) 本身是否能在理论上支持，之前有反馈过。

**Comment by XiaofengdiZhu** [comment]
> 可以先回退的 0.4.3 版本试一试。上周上了 一个feature 可能有些影响

解决一个新报错后（source目录错误），没有更多报错了，但vue组件里的东西变成一点都不索引，文章的其他部分正常

**Comment by ATQQ** [comment]
> > 可以先回退的 0.4.3 版本试一试。上周上了 一个feature 可能有些影响
> 
> 解决一个新报错后（source目录错误），没有更多报错了，但vue组件里的东西变成一点都不索引，文章的其他部分正常

可以 看一下你的组件咋写的嘛，你看看编译后那个组件内容是不是在 HTML的 VPContent 里，要SSG能渲染出来，ClientOnly 包裹的组件应该不会出现在HTML里

**Comment by ATQQ** [comment]
Get 周末我看一下

**Comment by ATQQ** [comment]
看了一下 索引是生成了的

<img width="1955" alt="image" src="https://github.com/user-attachments/assets/df465a4d-4ec7-4aac-b3d9-f88b2be51256">

功能不好用 是因为 pagefind 对中文的分词这块支持还有点弱

https://pagefind.app/docs/multilingual/#language-support

<img width="817" alt="image" src="https://github.com/user-attachments/assets/ad2156b6-64bf-4fba-89b0-cd806c971ead">

后面是有计划在前端侧引入一个分词的库看看效果

**Comment by XiaofengdiZhu** [comment]
请再看看我的说明\~ @ATQQ 
`只能索引到vue组件里最后一个h标签及其之后的内容`  
`后端输入`那块就是最后一个h标签之后的，前面的几个端口的内容是一点都搜不到

**Comment by ATQQ** [comment]
① lang="ts" 的问题已经修复了
② 检索内容我看了一下应该是检索到了的
<img width="447" alt="image" src="https://github.com/user-attachments/assets/473a55c8-8bb8-4a15-bc08-007c4563ca9b">
<img width="598" alt="image" src="https://github.com/user-attachments/assets/e0fc6188-9e32-450d-a89e-6cad4f503e08">

搜索无结果，那确实是库本身对中文支持的问题了。

中文的分词我默认已经调整成使用浏览器自带的了 [Intl.Segmenter](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter)，比原来效果应该会好一点。

③ 目前搜索结果展示策略是，针对一个页面的只展示匹配度最高的最后一条。

所以有下面这个问题。

`搜索每个端口都有的使用位宽，搜索结果中，该页的仅有后端输入里面的。`

这块我计划暴露一个配置，支持自定义要展示的条数或全部展示。

**Comment by XiaofengdiZhu** [comment]
谢谢！期待更新！

另外，配置还缺几个本地化字符串：`to select`、`to navigate`、`to close`、`Search by`

附让顶栏的搜索框更接近vitepress自带搜索框的css：
```css
.content-body > .blog-search > .nav-search-btn-wait {
    border-radius: 8px;
    padding: 0 10px 0 12px;
    background-color: var(--vp-c-bg-alt);
    width: 100%;
    height: 40px;

    &:hover {
        background: var(--vp-c-bg-alt);
    }

    & .search-tip {
        padding-left: 8px;
        padding-right: 16px;
    }

    & .metaKey {
        border: 1px solid var(--vp-c-divider);
        border-radius: 4px;
        padding: 0 6px;
    }
}
```
