### ISSUE TITLE
Page titles not being found by search

### ISSUE THREAD

**Issue by JoakimSeptima** [ATQQ/sugar-blog#317]
First, thank you for creating the vitepress-plugin-pagefind plugin. It has been a valuable tool for integrating search into our documentation projects :)

However, we have encountered an issue where the search does not seem to find the titles of any pages.

Details:
We have a project where the search will not find the title. The pages are set up in docs\page.md like this:

```yml
---
title:  "Lorem ipsum"
description: "dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
name: page
hidden: false
tags: [chart]
components:
  - chart
---

# Lorem ipsum

Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
```

docs\.vitepress\config.mts:
```js
import { defineConfig } from 'vitepress'
import { pagefindPlugin } from 'vitepress-plugin-pagefind'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: "vitepress search test",
  description: "A VitePress Site",
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Examples', link: '/markdown-examples' }
    ],

    sidebar: [
      {
        text: 'Examples',
        items: [
          { text: 'Markdown Examples', link: '/markdown-examples' },
          { text: 'Runtime API Examples', link: '/api-examples' },
          { text: 'Page', link: '/page'}
        ]
      }
    ],

    socialLinks: [
      { icon: 'github', link: 'https://github.com/vuejs/vitepress' }
    ]
  },
  vite: {
    plugins: [pagefindPlugin()],
  }
})
```

We tested by creating a new template project following the steps in your documentation, but the issue persists.

We are unsure if this is due to an error in our configuration or if it might be a bug in the plugin itself.
Could you kindly confirm if there are additional configurations we need to check, or if this is something you can look into? Any guidance would be greatly appreciated.

Thank you for your time and support.
