### ISSUE TITLE
请问主页头像的旋转功能可以关闭或自定义动画吗？

### ISSUE THREAD

**Issue by SIXiaolong1117** [ATQQ/sugar-blog#329]
没有找到相关的设置项。

我在想能否用 `style.scss` 进行样式重载。但是不太清楚 Selector 该怎么写。

**Comment by ATQQ** [comment]
可以重载，你可以在 调试工具中查看选择器

<img width="981" alt="Image" src="https://github.com/user-attachments/assets/ff3f2ca0-d010-466d-af2c-1890944bb3e2" />

```css
选择器:hover{
transform: none !important;
}
```
