### ISSUE TITLE
编写的其中一个文档引入css样式，发布时会导致全部md文件都引入这个样式

### ISSUE THREAD

**Issue by Windstarry** [ATQQ/sugar-blog#82]
我在其中一个文档中引入自动加标题的css样式
```css
<style type="text/css">
    h1 { counter-reset: h2counter; }
    h2 { counter-reset: h3counter; }
    h3 { counter-reset: h4counter; }
    h4 { counter-reset: h5counter; }
    h5 { counter-reset: h6counter; }
    h6 { }
    h2:before {
      counter-increment: h2counter;
      content: counter(h2counter) ".\0000a0\0000a0";
    }
    h3:before {
      counter-increment: h3counter;
      content: counter(h2counter) "."
                counter(h3counter) ".\0000a0\0000a0";
    }
    h4:before {
      counter-increment: h4counter;
      content: counter(h2counter) "."
                counter(h3counter) "."
                counter(h4counter) ".\0000a0\0000a0";
    }
    h5:before {
      counter-increment: h5counter;
      content: counter(h2counter) "."
                counter(h3counter) "."
                counter(h4counter) "."
                counter(h5counter) ".\0000a0\0000a0";
    }
    h6:before {
      counter-increment: h6counter;
      content: counter(h2counter) "."
                counter(h3counter) "."
                counter(h4counter) "."
                counter(h5counter) "."
                counter(h6counter) ".\0000a0\0000a0";
    }
</style>
```
dev的时候显示正常，build后每个md文件都加入了这个样式
特别是首页标题这里都自动加了数字
首页内容如下
```
layout: home
blog:
    name: windstarry的Blog
    motto: 记录学习,记录生活
    inspiring: 知识是一点一滴积累起来的...
    pageSize: 6
```
发布后显示
![FireShot Capture 003 - windstarry's blog - windstarry's blog - windstarry github io](https://user-images.githubusercontent.com/61078000/229264063-7a06edf7-852e-447e-ab5f-c57c3de74f03.png)
dev的显示
![FireShot Capture 004 - windstarry's blog - windstarry's blog - localhost](https://user-images.githubusercontent.com/61078000/229264070-17374ed6-2120-4d00-afea-720958293257.png)
